version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    container_name: postgresql-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: mysecretpassword
        DB_URL: jdbc:postgresql://db:5432/postgres
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8080:8080"


volumes:
  postgres-data:
