services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: my-postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     environment:
#       # These will be passed to your Spring Boot app inside the container
#       DB_USERNAME: postgres
#       DB_PASSWORD: postgres
#       DB_URL: jdbc:postgresql://db:5432/tasksdb # Connect to the 'db' service
#     ports:
#       - "8080:8080"
#     depends_on:
#       - db
# volumes:
#   postgres-data:
